/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_balamex_BalamexLib */

#ifndef _Included_com_example_balamex_BalamexLib
#define _Included_com_example_balamex_BalamexLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_balamex_BalamexLib
 * Method:    balamatorIOn
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_example_balamex_BalamexLib_balamatorIOn
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_balamex_BalamexLib
 * Method:    balamatorIOff
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_example_balamex_BalamexLib_balamatorIOff
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
